####Configuration du pool de connexion
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5

#### PostgreSQL
##Connexion local
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=
##Connexion kube
spring.datasource.url=jdbc:postgresql://localhost:5432/defaultdb
spring.datasource.username=postgres
spring.datasource.password=bmzujok4jwgshfok46iu